# Generated by Django 4.1.4 on 2022-12-22 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_alter_transaction_attempt_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="acct",
            field=models.ForeignKey(
                db_column="acct_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.account",
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="repayment_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="in_acct",
            field=models.ForeignKey(
                db_column="in_acct_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_acct",
                to="base.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="out_acct",
            field=models.ForeignKey(
                db_column="out_acct_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_acct",
                to="base.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="trans_no",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
