# Generated by Django 4.1.4 on 2022-12-24 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_account_user_alter_repayment_acct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repayment",
            name="acct",
            field=models.ForeignKey(
                db_column="acct_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.account",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="end_at",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 18, 17, 18, 58, 414501)
            ),
        ),
        migrations.AlterField(
            model_name="repayment",
            name="start_at",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 31, 17, 18, 58, 414501)
            ),
        ),
    ]
